### ISSUE TITLE
Logo Design  For Barnklock

### ISSUE THREAD

**Issue by zularizal** [walles/barnklocka#1]
Hello @walles , I am a graphic designer, I want to help you in graphic design.

After I review you need a logo/icon launcher on this project. Therefore I want to contribute to this project by creating a new logo / icons. What do you think?

**Comment by walles** [comment]
Here's the current one:
https://github.com/walles/barnklocka/blob/master/gfx/icon.png

If you have a better suggestion I'd be happy to have a look :)

  /Johan

**Comment by zularizal** [comment]
Okay, I'll design a new logo for you

**Comment by walles** [comment]
Some more context about the existing graphics:
https://github.com/walles/barnklocka/tree/master/gfx

**Comment by walles** [comment]
And you probably know this already, but this is an open source project that I made in my spare time, and there's no budget here for paying anything to anyone.

Looking forward to your suggestion :)

**Comment by zularizal** [comment]
I know, I also make it free for you

**Comment by zularizal** [comment]
Hi, I've made some sample logos for this, what do you think? Which one do you like? 

If you want something changed please let me know.
![logo](https://user-images.githubusercontent.com/38547278/41133107-2cc4c942-6aef-11e8-83f0-58beb51196a9.png)

**Comment by walles** [comment]
I like the first one best.

It signals that:
* The app is about the clock
* The clock is settable

Since this is an app for children to learn time, do you think it could be a bit more childish somehow? I don't have any concrete suggestions, but do consider it!

If I could also have the same thing:
* in 1024x1024
* white background
* the edges of the clock touching the edges of the image
* no hour marks, or dials and no hand

Then I could use that as the clock image for the actual app.

In the app, I want to draw the clock face and the dials myself, that's why the clock should be empty for that picture.

**Comment by zularizal** [comment]
I have changed some objects, so now it looks cute.
And the right, is that what you mean?

![g7435](https://user-images.githubusercontent.com/38547278/41152296-6fbd937a-6b3d-11e8-84f8-07b4dc6c158b.png)

**Comment by walles** [comment]
I think I actually liked your first suggestion (the not-cute one) better; this one feels a bit too girly.

I want my boy to use this as well when he gets older :).

So this one as an icon (512x512, PNG, optionally transparent background for relevant parts), and the same one with a blank face and no hand at 1024x1024 for in-app background, that would be super!

Thanks so much for working on this @zularizal :)

<img width="205" alt="skarmavbild 2018-06-08 kl 13 10 15" src="https://user-images.githubusercontent.com/158201/41155198-5601f43c-6b1d-11e8-8924-59498668245f.png">

**Comment by zularizal** [comment]
Hi @walles , I've uploaded the logo file and .png files to drive, check this link

https://drive.google.com/open?id=1i58wYHbpNPi6YoVPiAbz-z2rDZexqiqi

And also I have sent a pull request for you #2
